### ISSUE TITLE
Host key verification failed

### ISSUE THREAD

**Issue by mochadwi** [spyoungtech/mirror-action#13]
```
+ git config --global core.sshCommand 'ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -o UserKnownHostsFile=~/.ssh/known_hosts'
+ git remote add mirror git@gitlab.com:sampingan-mobile/dynamic-ui.git
+ [[ false != \f\a\l\s\e ]]
+ [[ true != \t\r\u\e ]]
+ eval git push -u --tags --force --prune mirror
++ git push -u --tags --force --prune mirror
Host key verification failed.
```

Shouldn't this line use `~/.ssh/id_rsa.pub` instead of `~/.ssh/id_rsa`? cmiiw
```
+ git config --global core.sshCommand 'ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -o UserKnownHostsFile=~/.ssh/known_hosts'
```

Also IMHO, it's necessary to provide `GIT_SSH_PUBLIC_KEY` env var as well, so this is created instead
```
+ chmod 600 /github/home/.ssh/id_rsa.pub // this is created, if providing GIT_SSH_PUBLIC_KEY, otherwise only the private keys: id_rsa
+ chmod 600 /github/home/.ssh/id_rsa
```

See my workflow logs here: https://github.com/sampingantech/dynamic-ui/runs/1255564326?check_suite_focus=true#step:4:223

**Comment by mochadwi** [comment]
Thus the `GIT_USERNAME` also required to provide? @spyoungtech

**Comment by mochadwi** [comment]
I'm curious with this section: https://github.com/spyoungtech/mirror-action#mirror-a-repository-using-ssh

`knowns_hosts` seems not working in my place, even already added both gitlab.com & github.com.

Should I also whitelist the IP/host where you host your docker image? @spyoungtech

**Comment by mochadwi** [comment]
because using `GIT_SSH_NO_VERIFY_HOST: "true"` fix my issue

**Comment by spyoungtech** [comment]
@mochadwi sorry for the delay in response. `known_hosts` is expected to be the contents of a `known_hosts` file, containing IP addresses and public keys, not just hostnames.
