### ISSUE TITLE
Fix compatibility with GitHub Actions 2.0

### ISSUE THREAD

**Issue by artob** [spyoungtech/mirror-action#3]
The release of [GitHub Actions 2.0](https://github.blog/2019-08-08-github-actions-now-supports-ci-cd/) appears to have broken this GitHub Action:

<img width="1113" alt="Screen Shot 2019-08-09 at 20 27 32" src="https://user-images.githubusercontent.com/4963/62797336-2524f680-bae4-11e9-902b-4e0da3e2375c.png">

See https://github.com/conreality/conreality-android/runs/189865639

The specific error from the Docker container is _"fatal: ref HEAD is not a symbolic ref"_, which appears to be related to the detached HEAD state that GitHub initializes the Git checkout with in the previous step.

**Comment by spyoungtech** [comment]
Thanks for bringing this up. I'll look into this and see if I can find the solution.

At first glance, it doesn't seem there's any way to configure GitHub's checkout behavior, so it looks like the change will have to be made to the action itself.

On initial thought is that maybe I can do a `git checkout $GITHUB_REF` ([ref](https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#runtime-environment-resources)) which, if the git ref is available, should checkout the branch/tag that triggered the workflow and avoid that fatal error.

**Comment by perkoren** [comment]
First of all thank you for this very useful project. 
I was facing the same issue, and after some struggling was able to get it to work with Github Actions 2.0.

https://github.com/perkoren/mirror-action

**Comment by spyoungtech** [comment]
@perkoren thank you that looks great! Please feel free to open a PR and I'll be happy to review and merge.

**Comment by spyoungtech** [comment]
#4 resolves this issue! Thanks again @perkoren
